### ISSUE TITLE
ThreeDGaussians plugin ?

### ISSUE THREAD

**Issue by iliesaya** [Akiya-Research-Institute/3dGaussiansPlugin-Demo#2]
Opening the ThreeDGaussiansDemo.uproject display this message ?

This project requires the ThreeDGaussians plugin.
Would you like to download it from the Unreal Engine Marketplace?

Clicking yes goes to a 404 page not found . 

What to do ?

**Comment by softyoda** [comment]
I have the same issue, the unreal link doesn't work and there are no plugin content in the project directory.

**Comment by iliesaya** [comment]
OK i understand now , the plugin is not free https://vrlab.akiya-souken.co.jp/en/products/threedgaussianplugin/ and it's not published yet on the marketplace .

**Comment by KenjiAsaba** [comment]
It is now available at [UE marketplace](https://www.unrealengine.com/marketplace/ja/product/410c8105b3aa41d38ab68660295bd7f3).
